### ISSUE TITLE
Error when running build

### ISSUE THREAD

**Issue by noahfreedman** [sphinx-contrib/sphinxcontrib-versioning#58]
I get the following error when trying to run this program:

```
sh-3.2# sphinx-versioning build -r 'v3.0' docs/ docs/_build/html/
=> Reading config from docs/conf.py...
/Library/Python/2.7/site-packages/sphinxcontrib/versioning/sphinx_.py:202: RemovedInSphinx20Warning: `sphinx.build_main()` has moved to `sphinx.cmd.build.build_main()`.
  result = build_main(argv)
Running Sphinx v1.8.2

Exception occurred:
  File "/Library/Python/2.7/site-packages/sphinx/config.py", line 204, in read
    return cls(namespace, overrides or {})
TypeError: __init__() takes exactly 5 arguments (3 given)
The full traceback has been saved in /tmp/sphinx-err-jLv6Vi.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Process Process-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Python/2.7/site-packages/sphinxcontrib/versioning/sphinx_.py", line 219, in _read_config
    _build(argv, config, Versions(list()), current_name, False)
  File "/Library/Python/2.7/site-packages/sphinxcontrib/versioning/sphinx_.py", line 204, in _build
    raise SphinxError
SphinxError
=> sphinx-build failed for branch/tag while reading config: <local>
=> Unable to read file, continuing with only CLI args.
=> Gathering info about the remote git repository...
=> Getting list of all remote branches/tags...
=> Found: master v3.0 2.1 3.0
=> With docs: master
=> Root ref v3.0 not found in: master
Failure.
sh-3.2# git branch
* master
  v3.0
sh-3.2# git checkout -b v2.0
Switched to a new branch 'v2.0'
sh-3.2# git status
On branch v2.0
nothing to commit, working tree clean
sh-3.2# git push origin v2.0
Total 0 (delta 0), reused 0 (delta 0)
remote:
remote: To create a merge request for v2.0, visit:
remote:   https://git.nucleos.com/portablecloud/docs/api-internal/merge_requests/new?merge_request%5Bsource_branch%5D=v2.0
remote:
To git.nucleos.com:portablecloud/docs/api-internal.git
 * [new branch]      v2.0 -> v2.0
sh-3.2# git status
On branch v2.0
nothing to commit, working tree clean
sh-3.2# sphinx-versioning build -r 'v3.0' docs/ docs/_build/html/
=> Reading config from docs/conf.py...
/Library/Python/2.7/site-packages/sphinxcontrib/versioning/sphinx_.py:202: RemovedInSphinx20Warning: `sphinx.build_main()` has moved to `sphinx.cmd.build.build_main()`.
  result = build_main(argv)
Running Sphinx v1.8.2

Exception occurred:
  File "/Library/Python/2.7/site-packages/sphinx/config.py", line 204, in read
    return cls(namespace, overrides or {})
TypeError: __init__() takes exactly 5 arguments (3 given)
The full traceback has been saved in /tmp/sphinx-err-5cAybs.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Process Process-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Python/2.7/site-packages/sphinxcontrib/versioning/sphinx_.py", line 219, in _read_config
    _build(argv, config, Versions(list()), current_name, False)
  File "/Library/Python/2.7/site-packages/sphinxcontrib/versioning/sphinx_.py", line 204, in _build
    raise SphinxError
SphinxError
=> sphinx-build failed for branch/tag while reading config: <local>
=> Unable to read file, continuing with only CLI args.
=> Gathering info about the remote git repository...
=> Getting list of all remote branches/tags...
=> Found: master v2.0 v3.0 2.1 3.0
=> With docs: master v2.0
=> Root ref v3.0 not found in: master v2.0
Failure.
sh-3.2# sphinx-versioning build -r 'v2.0' docs/ docs/_build/html/
=> Reading config from docs/conf.py...
/Library/Python/2.7/site-packages/sphinxcontrib/versioning/sphinx_.py:202: RemovedInSphinx20Warning: `sphinx.build_main()` has moved to `sphinx.cmd.build.build_main()`.
  result = build_main(argv)
Running Sphinx v1.8.2

Exception occurred:
  File "/Library/Python/2.7/site-packages/sphinx/config.py", line 204, in read
    return cls(namespace, overrides or {})
TypeError: __init__() takes exactly 5 arguments (3 given)
The full traceback has been saved in /tmp/sphinx-err-i2yAWf.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Process Process-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Python/2.7/site-packages/sphinxcontrib/versioning/sphinx_.py", line 219, in _read_config
    _build(argv, config, Versions(list()), current_name, False)
  File "/Library/Python/2.7/site-packages/sphinxcontrib/versioning/sphinx_.py", line 204, in _build
    raise SphinxError
SphinxError
=> sphinx-build failed for branch/tag while reading config: <local>
=> Unable to read file, continuing with only CLI args.
=> Gathering info about the remote git repository...
=> Getting list of all remote branches/tags...
=> Found: master v2.0 v3.0 2.1 3.0
=> With docs: master v2.0
=> Root ref is: v2.0
=> Pre-running Sphinx to collect versions' master_doc and other info.
/Library/Python/2.7/site-packages/sphinxcontrib/versioning/sphinx_.py:202: RemovedInSphinx20Warning: `sphinx.build_main()` has moved to `sphinx.cmd.build.build_main()`.
  result = build_main(argv)
Running Sphinx v1.8.2

Exception occurred:
  File "/Library/Python/2.7/site-packages/sphinx/config.py", line 204, in read
    return cls(namespace, overrides or {})
TypeError: __init__() takes exactly 5 arguments (3 given)
The full traceback has been saved in /tmp/sphinx-err-4o1NJZ.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Process Process-2:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Python/2.7/site-packages/sphinxcontrib/versioning/sphinx_.py", line 204, in _build
    raise SphinxError
SphinxError
=> sphinx-build failed for branch/tag: v2.0
Failure.
```

**Comment by MXWXZ** [comment]
This repo is about 3 years without maintenance, I got the same error. Maybe you can try lower version of sphinx :(
Waiting to be fixed.

**Comment by MXWXZ** [comment]
> Don't hold your breath, I think this repo is dead.
> 
> But this fork works (at least for me): https://github.com/leokoppel/sphinxcontrib-versioning
> 
> (which I found from #57)

+rep this one works.

**Comment by MXWXZ** [comment]
> > Don't hold your breath, I think this repo is dead.
> > But this fork works (at least for me): https://github.com/leokoppel/sphinxcontrib-versioning
> > (which I found from #57)
> 
> @MXWXZ, @odoublewen, shouldn't we create an "official" fork, maintain it, and make it available in PyPI? It would be very useful to me and others hosting pages on gitlab, given that gitlab has an integrated CI.

The repo is too old and you need to do a lot of things to fix the CI error or anything else.
You can use

    pip install git+[YOUR GIT URL]

I think its enough for me :)

**Comment by odoublewen** [comment]
> shouldn't we create an "official" fork, maintain it, and make it available in PyPI?

@sehnem  This is a good goal.  I don't have the bandwidth right now.  I am also not sure how one would go about making it available on PyPI.  Would you give it a new name to distinguish it from the dead project?  And how would the people find out that the fork was the "official" one?  In general, it seems like zombie projects, owned by an individual, are a weakness of github for opensource.  It would be good if there was a way to call out the defunct status.

Anyway.  Maybe talk to @leokoppel since that's where the working code is?
